language: node_js
matrix:
  include:
    - node_js: "0.10"
      env: "NODE_FLAGS='' SCRIPT_FLAGS=''"
    - node_js: "0.11"
      env: "NODE_FLAGS='--harmony' SCRIPT_FLAGS=''"
    - node_js: "0.10"
      env: "NODE_FLAGS='' SCRIPT_FLAGS='--saucelabs'"
  fast_finish: true

install: 'npm --force install acorn bluebird browserify cli-table cross-spawn glob grunt-saucelabs jshint jshint-stylish mkdirp mocha open optimist rimraf semver-utils serve-static sinon text-table uglify-js'
before_script:
- git submodule update --init --recursive
script: "node $NODE_FLAGS tools/test.js $SCRIPT_FLAGS"
